CREATE TABLE USER
(    USERID   		 INT   	 NOT NULL AUTO_INCREMENT,
    EMAIL   		 VARCHAR(255)    NOT NULL UNIQUE,
    PASSWORD   	 VARCHAR(32)    NOT NULL,
    ROLE   		 VARCHAR(32),
    VALIDATED   	 TINYINT   	 NOT NULL DEFAULT 0,
PRIMARY KEY(USERID)
) ENGINE=InnoDB;

CREATE TABLE ADVISOR_SETTINGS
(    USERID   	 INT   	 NOT NULL,
    PNAME   	 VARCHAR(32)    NOT NULL,
    EMAIL   	 VARCHAR(255)    NOT NULL,
    NOTIFICATION    VARCHAR(45)    NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;    

CREATE TABLE APPOINTMENT_TYPES
(    USERID   	 INT   	 NOT NULL,
    TYPE   	 VARCHAR(45)    NOT NULL,
    DURATION    INT   	 NOT NULL,
PRIMARY KEY(USERID,TYPE),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE ADVISING_SCHEDULE
(    ID   	 INT   	 NOT NULL AUTO_INCREMENT,
    USERID   	 INT   	 NOT NULL,
    ADVISING_DATE    DATE   	 NOT NULL,
    ADVISING_STARTTIME    TIME   	 NOT NULL,
    ADVISING_ENDTIME    TIME   	 NOT NULL,
    STUDENTID    INT,
PRIMARY KEY(ID),
FOREIGN KEY(USERID) REFERENCES USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE APPOINTMENTS
(    ID   	 INT   	 NOT NULL,
    ADVISOR_USERID    INT   	 NOT NULL,
    STUDENT_USERID    INT   	 NOT NULL,
    ADVISING_DATE    DATE   	 NOT NULL,
    ADVISING_STARTTIME    TIME    NOT NULL,
    ADVISING_ENDTIME    TIME    NOT NULL,
    APPOINTMENT_TYPE    VARCHAR(45)    NOT NULL,
    STUDENTID    INT   	 NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ADVISOR_USERID) REFERENCES USER(USERID),
FOREIGN KEY(STUDENT_USERID) REFERENCES USER(USERID),
FOREIGN KEY(ADVISOR_USERID,APPOINTMENT_TYPE) REFERENCES APPOINTMENT_TYPES(USERID,TYPE)
) ENGINE=InnoDB;

CREATE TABLE DEPARTMENT_SETTINGS
(    ID   	 INT   	 NOT NULL,
    NAME   	 VARCHAR(45)    NOT NULL,
    ADVISING_START    TIME,
    ADVISING_END    TIME,
PRIMARY KEY(ID)
) ENGINE=InnoDB;


INSERT INTO USER (email,password,role,validated) VALUES('testadvisor@uta.edu','test1234','advisor',1);
INSERT INTO USER (email,password,role,validated) VALUES('testadvisor2@uta.edu','test1234','advisor',1);
INSERT INTO USER (email,password,role,validated) VALUES('testadvisor3@uta.edu','test1234','advisor',1);
INSERT INTO USER (email,password,role,validated) VALUES('teststudent@mavs.uta.edu','test1234','student',1);
INSERT INTO USER (email,password,role,validated) VALUES('teststudent2@mavs.uta.edu','test1234','student',1);
INSERT INTO USER (email,password,role,validated) VALUES('teststudent3@mavs.uta.edu','test1234','student',1);
INSERT INTO USER (email,password,role,validated) VALUES('teststudent4@mavs.uta.edu','test1234','student',1);
INSERT INTO USER (email,password,role,validated) VALUES('teststudent@mavs.uta.edu','test1234','student',1);
INSERT INTO USER (email,password,role,validated) VALUES('testadmin@uta.edu','test1234','admin',1);
INSERT INTO USER (email,password,role,validated) VALUES('testfaculty@uta.edu','test1234','faculty',1);
INSERT INTO APPOINTMENT_TYPES (USERid,type,duration) VALUES(1,'Drop Class',5);
INSERT INTO APPOINTMENT_TYPES (USERid,type,duration) VALUES(1,'Add Class',5);
INSERT INTO APPOINTMENT_TYPES (USERid,type,duration) VALUES(1,'Transfer Student',10);
INSERT INTO ADVISOR_SETTINGS VALUES(1,'Test Adv 1','testadvisor@uta.edu','day');
INSERT INTO ADVISOR_SETTINGS VALUES(2,'Test Adv 2','testadvisor2@uta.edu','day');
INSERT INTO ADVISOR_SETTINGS VALUES(3,'Test Adv 3','testadvisor3@uta.edu','day');
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:00","09:05",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:05","09:10",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:10","09:15",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:15","09:20",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:20","09:25",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:25","09:30",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:30","09:35",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:35","09:40",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:40","09:45",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:45","09:50",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:50","09:55",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","09:55","10:00",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","10:00","10:05",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-10","10:05","10:10",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:00","09:05",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:05","09:10",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:10","09:15",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:15","09:20",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:20","09:25",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:25","09:30",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:30","09:35",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:35","09:40",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:40","09:45",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:45","09:50",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:50","09:55",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","09:55","10:00",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","10:00","10:05",null);
INSERT INTO ADVISING_SCHEDULE (USERID,ADVISING_DATE,ADVISING_STARTTIME,ADVISING_ENDTIME,STUDENTID) VALUES(1,"2014-9-11","10:05","10:10",null);

